name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install packages
        run: |
          npm ci
          npm install -g @angular/cli

      # - name: Test
      #   run: npm test

      - name: Lint
        run: npm run lint

      - name: Credentials for deployment
        run: |
          git config --global user.email "${{ secrets.email }}"
          git config --global user.name "${{ github.event.schedule.user.login }}"

      - name: build
        run: ng deploy --no-silent --base-href https://${{ github.event.schedule.user.login }}.github.io/${{ github.event.repository.name }}/

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: App deployed. Well done ✔️
